//1.	Convert a random number generated by JavaScript to a number in the range 1 to 50
var randomNumber = Math.floor(Math.random() * 50) + 1;

//2.	Generate a random number and assign it to a variable that hasn't been declared beforehand.
var randomValue = Math.random(); // Generates a random number between 0 (inclusive) and 1 (exclusive)

//3.	You have to create a dice in JavaScript with the use of pseudo-random number.
var diceRoll = Math.floor(Math.random() * 6) + 1;

//4.	You have to create a toss (head/tail) in JavaScript with the use of pseudo-random number.
var coinToss = Math.random() < 0.5 ? 'Heads' : 'Tails';
